# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5b5ebbfdd6362b0f68d47ca4d29da041a8c59e5b4b522984732ca078b80752bc17c48e14a50f2c45803c3a733837aa177659f4dd9bcef87f94c545a813fa9d4

test:
  secret_key_base: e71cdbdbe7a6a9f25843f1635af59474c9b9744a5b6f31f885a9be2f18d2329ab5c151c74535b16fb9cf9cc75590c330163e9b1631cbff420fcd8a4c57c9cb35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
